dlhong/-TODO

app/models/activity.rb
app/models/activity_participant.rb
app/models/activity_type.rb
app/models/participant.rb
app/models/posting.rb
app/models/review.rb
app/models/saving.rb
app/models/type.rb
app/models/user.rb
db/migrate/20220820082410_create_types.rb
db/migrate/20220820082412_create_activities.rb
db/migrate/20220820083410_create_participants.rb
db/migrate/20220820083732_create_activity_participants.rb
db/migrate/20220820083733_update_users.rb
db/migrate/20220820090417_create_savings.rb
db/migrate/20220820090852_create_reviews.rb
db/migrate/20220820091050_create_postings.rb
db/migrate/20220820092328_create_activity_types.rb
db/schema.rb
test/models/activity_participant_test.rb
test/models/activity_test.rb
test/models/activity_type_test.rb
test/models/participant_test.rb
test/models/posting_test.rb
test/models/review_test.rb
test/models/saving_test.rb
test/models/type_test.rb

models and database

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb

Pundit gem is added but not functional for now

pundit is added, but not functional

---

app/controllers/activities_controller.rb
config/routes.rb
test/controllers/activities_controller_test.rb

activity controller with index func

activity conntroller index func

---

Gemfile.lock
app/views/shared/_navbar.html.erb

created navbar

---

app/controllers/activities_controller.rb
app/views/activities/index.html.erb
config/routes.rb

activity controller and route

---

app/controllers/activities_controller.rb

no log in for index page

---

Gemfile.lock

gemlock file

---

app/controllers/activities_controller.rb

new create activity

---

app/controllers/savings_controller.rb
app/views/pages/home.html.erb
config/routes.rb
test/controllers/savings_controller_test.rb

New, create and destroy funcs are added. Routes are modified accordingly.

saving controller; new,create, destory funcs are added. Routes are done

---

app/controllers/reviews_controller.rb
config/routes.rb
test/controllers/reviews_controller_test.rb

reviews controller added. routes are updated

review contoller is added

---

app/controllers/reviews_controller.rb
app/models/activity.rb
app/models/participant.rb
app/models/posting.rb
app/models/review.rb
app/models/saving.rb
app/models/type.rb
app/models/user.rb
db/migrate/20220820092329_update_reviews.rb
db/schema.rb
test/controllers/types_controller_test.rb

validations are added. schema has been updated.

validations part 1

---

app/controllers/activities_controller.rb
config/routes.rb

activity show func.

---

app/models/user.rb
app/views/activities/show.html.erb

validations and show

---

app/controllers/users/registrations_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
config/routes.rb

User registration controller was created. On the page FirstName, LastName, and Address fields were added

user registration has been changed

---

app/controllers/activities_controller.rb
app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

A user can log out now

---

app/controllers/activities_controller.rb
app/controllers/savings_controller.rb
app/models/saving.rb
app/views/activities/show.html.erb

saving func

---

app/controllers/savings_controller.rb
app/views/savings/index.html.erb
config/routes.rb

Attendance

---

app/controllers/savings_controller.rb
app/views/activities/show.html.erb
app/views/savings/index.html.erb
app/views/shared/_navbar.html.erb

routes and stuff

---

app/controllers/savings_controller.rb
app/views/savings/index.html.erb
config/routes.rb

delete update savings

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/activities/show.html.erb

fixed some of show frontend

---

app/assets/stylesheets/components/_btn-orange.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_savingsindex.scss
app/assets/stylesheets/pages/_show.scss
app/views/savings/index.html.erb

fixed some frontend here and there

some frontend hehe

---

app/views/pages/home.html.erb
app/views/shared/_cardview.html.erb
app/views/shared/_navbar.html.erb

The average of the ratings is now calculated. Sets the default value of 3 if there are no reviews on any activity.

aerage of the ratings calculated

---

Gemfile
Gemfile.lock
app/models/activity.rb
config/environments/development.rb
config/storage.yml
db/migrate/20220903102244_create_active_storage_tables.active_storage.rb
db/schema.rb

added cloudinary

---

db/schema.rb
yarn.lock

resolving conflicts

---

app/controllers/activities_controller.rb

Map result

---

db/seeds.rb

seed number 30

---

app/assets/stylesheets/components/_cardview.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_slidercard.scss
app/assets/stylesheets/components/_swiper.scss
app/views/pages/home.html.erb
app/views/shared/_cardview.html.erb
app/views/shared/_slidercard.html.erb

I fixed the card layouts in the slider

fixed cards in slider

---

app/assets/stylesheets/components/_cardview.scss
app/views/shared/_cardview.html.erb

fixed review position in indexcards

fxed indexcards

---

app/views/shared/_cardsaving.html.erb

fixed the images on profile page savings

fixed image on profile page

---

app/views/activities/show.html.erb
app/views/shared/_slidercard.html.erb

image cards

---

app/views/shared/_cardsaving.html.erb

fixd savingscard

---

app/views/shared/_navbar.html.erb

some update on search and log in button visibilty

some update on search and log in buttons

---

app/controllers/reviews_controller.rb
app/models/review.rb
app/views/activities/show.html.erb
db/migrate/20220913183813_add_title_to_reviews.rb
db/schema.rb

users and reviewws

---

app/models/activity.rb
app/views/activities/show.html.erb
db/migrate/20220915162802_add_types_to_activity.rb
db/schema.rb
db/seeds.rb

average on show page

---

app/views/activities/_info_window.html.erb

Map optimisation
